test_that("multiallelic text formats retain counts and allele pairs", {
  f <- export_fixture()
  on.exit({SeqArray::seqClose(f$gds); unlink(f$path)}, add = TRUE)
  folder <- tempfile(); dir.create(folder)
  on.exit(unlink(folder, recursive = TRUE), add = TRUE)
  before <- SeqArray::seqGetFilter(f$gds)
  s <- write_structure(f$gds, strata=f$strata, filename="s", path.folder=folder, verbose=FALSE)
  lines <- readLines(s$files[1])
  expect_length(lines, 9)
  expect_equal(lines[2:3], c("S1\t1\t1\t1\t2", "S1\t1\t1\t1\t3"))
  h <- write_hierfstat(f$gds, strata=f$strata, filename="h", path.folder=folder, verbose=FALSE)
  r <- read_fstat(attr(h,"export.files")[1])
  expect_true("002003" %in% r$GENOTYPE)
  expect_equal(nrow(r), 12)
  b <- write_bayescan(f$gds, strata=f$strata, filename="b", path.folder=folder, verbose=FALSE)
  lines <- readLines(b$files[1])
  expect_true("1 4 2 3 1" %in% lines)
  expect_true("3 2 3 0 1 1" %in% lines)
  expect_false(any(grepl("GENE_N",lines)))
  expect_identical(SeqArray::seqGetFilter(f$gds),before)
})

test_that("biallelic exporters use the documented orientations", {
  f <- export_fixture(incomplete=TRUE)
  on.exit({SeqArray::seqClose(f$gds); unlink(f$path)}, add=TRUE)
  SeqArray::seqSetFilter(f$gds,variant.id=1:2,verbose=FALSE)
  folder<-tempfile();dir.create(folder)
  on.exit(unlink(folder,recursive=TRUE),add=TRUE)
  pc<-write_pcadapt(f$gds,filename="pc",path.folder=folder,verbose=FALSE)
  expect_equal(unname(pc$genotype.matrix[1,]),c(0,1,2,1))
  expect_equal(pc$genotype.matrix[2,1],9,ignore_attr=TRUE)
  hm<-write_hapmap(f$gds,filename="hm",path.folder=folder,verbose=FALSE)
  z<-strsplit(readLines(hm$files[1]),"\t")
  expect_true(all(lengths(z)==15))
  expect_equal(z[[2]][12:15],c("AA","AG","GG","AG"))
  expect_equal(z[[3]][12],"NN")
  st<-write_stockr(f$gds,strata=f$strata,verbose=FALSE)
  expect_equal(unname(st[1,]),c(0,1,2,1))
  hz<-write_hzar(f$gds,strata=f$strata,
    distances=data.frame(STRATA=rev(unique(f$strata$STRATA)),Distance=c(20,10)),
    filename="hz",path.folder=folder,verbose=FALSE)
  expect_equal(hz$Distance,c(10,20))
  expect_equal(hz$L1.freq,c(.25,.75))
  expect_equal(hz$L2.n,c(1L,2L))
})

test_that("adegenet objects roundtrip without splitting locus labels", {
  skip_if_not_installed("adegenet")
  f<-export_fixture()
  on.exit({SeqArray::seqClose(f$gds);unlink(f$path)},add=TRUE)
  gi<-write_genind(f$gds,strata=f$strata)
  adegenet::locNames(gi)<-c("NC.1","NC.2","NC.3")
  r<-read_genind(gi,gds=FALSE)
  expect_equal(unique(r$MARKERS),c("NC.1","NC.2","NC.3"))
  expect_equal(r$GT[r$INDIVIDUALS=="s1" & r$MARKERS=="NC.3"],"001002")
  # genind owns its allele order; recover labels from its dictionary.
  expect_equal(sort(attr(r,"allele_dictionary")[["NC.3"]]),c("1","2","3"))
  SeqArray::seqSetFilter(f$gds,variant.id=1:2,verbose=FALSE)
  gl<-write_genlight(f$gds,strata=f$strata)
  r<-read_genlight(gl,gds=FALSE)
  expect_equal(r$ALT_DOSAGE[1:4],c(0,1,2,1))
  adegenet::ploidy(gl)<-1L
  expect_error(read_genlight(gl,gds=FALSE),"diploid")
})

test_that("SNPRelate and LDna close temporary files and preserve selections", {
  skip_if_not_installed("SNPRelate")
  f<-export_fixture()
  on.exit({SeqArray::seqClose(f$gds);unlink(f$path)},add=TRUE)
  SeqArray::seqSetFilter(f$gds,variant.id=1:2,verbose=FALSE)
  before<-SeqArray::seqGetFilter(f$gds)
  folder<-tempfile();dir.create(folder)
  on.exit(unlink(folder,recursive=TRUE),add=TRUE)
  g<-write_snprelate(f$gds,filename="snp",path.folder=folder,verbose=FALSE)
  gt<-SNPRelate::snpgdsGetGeno(g,snpfirstdim=TRUE,verbose=FALSE)
  SNPRelate::snpgdsClose(g)
  expect_equal(as.integer(gt[1,]),c(2L,1L,0L,1L))
  ld<-write_ldna(f$gds,verbose=FALSE)
  expect_true(all(is.na(ld[upper.tri(ld,diag=TRUE)])))
  expect_true(is.finite(ld[2,1]))
  expect_identical(SeqArray::seqGetFilter(f$gds),before)
})

test_that("FSTAT validates allele widths and metadata bounds", {
  expect_error(read_fstat(data.frame(x=c("1 1 2 2","L","1 0109"))),"maximum")
  expect_error(read_fstat(data.frame(x=c("1 1 2 2","L","2 0101"))),"Population")
  expect_error(read_fstat(data.frame(x=c("1 1 2 2","L","1 011"))),"width")
  x <- read_fstat(data.frame(x=c("1 1 12 2","L","1 0112")))
  expect_equal(x$GENOTYPE,"001012")
})

test_that("gtypes writing has a live roundtrip when strataG is installed", {
  skip_if_not_installed("strataG")
  f<-export_fixture()
  on.exit({SeqArray::seqClose(f$gds);unlink(f$path)},add=TRUE)
  x<-write_gtypes(f$gds,strata=f$strata,verbose=FALSE)
  expect_s4_class(x,"gtypes")
  y<-read_gtypes(x)
  expect_equal(nrow(y),12)
  expect_true("002003" %in% y$GT)
})
