# Detect if markers are biallelic

#' @name detect_biallelic_markers

#' @title Detect biallelic data

#' @description Detect whether markers in tidy genomic data or a GDS are
#' biallelic. Used internally in \pkg{genometranslator}
#' and might be of interest for users.

#' @param data (4 options) A file or object generated by radr:
#' \itemize{
#' \item tidy data
#' \item Genomic Data Structure (GDS)
#' }
#'
#' \emph{How to get GDS and tidy data ?}
#' Look into \code{\link{tidy_genome}},
#' \code{\link{read_vcf}} or
#' \code{\link{tidy_vcf}}.

#' @param verbose (optional, logical) \code{verbose = TRUE} to be chatty
#' during execution.
#' Default: \code{verbose = FALSE}.

#' @param parallel.core (optional) The number of core used for parallel
#' execution.
#' Default: \code{parallel.core = parallel::detectCores() - 1}.

#' @return A logical character string (TRUE/FALSE). That answer the question if
#' the data set is biallelic or not.

#' @export
#' @rdname detect_biallelic_markers
#' @author Thierry Gosselin \email{thierrygosselin@@icloud.com}

detect_biallelic_markers <- function(data, verbose = FALSE, parallel.core = parallel::detectCores() - 1) {

  # Checking for missing and/or default arguments ------------------------------
  if (missing(data)) rlang::abort("Input file missing")

  # Detect format --------------------------------------------------------------
  data.type <- detect_genomic_format(data)
  if (!data.type %in% c("tbl_df", "fst.file", "SeqVarGDSClass", "gds.file")) {
    rlang::abort("Input not supported for this function: read function documentation")
  }

  if (data.type %in% c("SeqVarGDSClass", "gds.file")) {
    if (data.type == "gds.file") {
      data <- read_genome(data, verbose = verbose)
      data.type <- "SeqVarGDSClass"
    }

    biallelic.node <- gdsfmt::index.gdsn(
      node = data,
      path = genome_metadata_path(data, child = "biallelic"),
      silent = TRUE
    )
    biallelic <- if (is.null(biallelic.node)) NULL else gdsfmt::read.gdsn(biallelic.node)
    if (!is.logical(biallelic) || length(biallelic) != 1L) biallelic <- NULL

    if (is.null(biallelic)) {
      safe_ref <- purrr::safely(.f = SeqArray::seqGetData)
      ref.safe <- safe_ref(gdsfile = data, var.name = "$ref")
      if (is.null(ref.safe$error)) {
        ref <- ref.safe$result
        sample.size <- min(length(unique(ref)), 100)
        biallelic <- max(unique(stringi::stri_count_regex(
          str = sample(
            x = unique(ref),
            size = sample.size), pattern = "[A-Z]"))) == 1
        sample.size <- ref <- NULL
      } else {
        biallelic <- FALSE
        ref <- max(SeqArray::seqGetData(gdsfile = data, var.name = "$num_allele"))
        if (ref == 2L) biallelic <- TRUE
      }

    }

    if (biallelic) {
      if (verbose) message("Data is bi-allelic")
    } else {
      if (verbose) message("Data is multi-allelic")
    }
    data <- biallelic

  } else {
    # Import data ---------------------------------------------------------------
    if (is.vector(data)) data %<>% read_genome(data = ., import.metadata = TRUE)

    if (rlang::has_name(data, "ALT_DOSAGE")) {
      data <- TRUE
      if (verbose) message("Data is bi-allelic")
    } else {
      # necessary steps to make sure we work with unique markers and not duplicated LOCUS
      if (rlang::has_name(data, "LOCUS") && !rlang::has_name(data, "MARKERS")) {
        data %<>% dplyr::rename(MARKERS = LOCUS)
      }

      # Remove markers for which every genotype is missing before counting
      # alleles. This is a structural preparation step and has no filtering
      # side effects or output files.
      detect.gt <- detect_gt(x = data, keep.one = TRUE)
      genotype <- data[[detect.gt]]
      genotyped <- if (detect.gt == "ALT_DOSAGE") {
        !is.na(genotype)
      } else if (detect.gt == "GT") {
        !is.na(genotype) & genotype != "000000"
      } else {
        !is.na(genotype) & genotype != "./."
      }
      keep.markers <- unique(data$MARKERS[genotyped])
      data <- dplyr::filter(data, MARKERS %in% keep.markers)

      # Detecting biallelic markers-------------------------------------------------
      if (verbose) message("Scanning for number of alleles per marker...")
      if (rlang::has_name(data, "ALT")) {
        alt.num <- max(unique(
          stringi::stri_count_fixed(str = unique(data$ALT), pattern = ","))) + 1

        if (alt.num > 1) {
          data <- FALSE
          if (verbose) message("Data is multi-allelic")
        } else {
          data <- TRUE
          if (verbose) message("Data is bi-allelic")
        }
        alt.num <- NULL
      } else {
        # If there are less than 100 markers, sample all of them
        sampled.markers <- unique(data$MARKERS)
        n.markers <- length(sampled.markers)
        if (!n.markers < 100) {
          # otherwise 30% of the markers are randomly sampled
          # small.panel <- FALSE
          sampled.markers <- sample(
            x = sampled.markers,
            size = length(sampled.markers) * 0.30,
            replace = FALSE)
          n.markers <- length(sampled.markers)
        }

        # Allows to have either GT, GT_VCF_NUC, GT_VCF or ALT_DOSAGE
        # If more than 1 is discovered in data, keep 1 randomly.
        detect.gt <- detect_gt(x = data) #utils
        want <- c("MARKERS", detect.gt)
        data %<>% dplyr::select(dplyr::any_of(want))

        if (rlang::has_name(data, "GT")) {
          data %<>%
            dplyr::select(MARKERS, GT) %>%
            dplyr::filter(GT != "000000") %>%
            dplyr::filter(MARKERS %in% sampled.markers) %>%
            dplyr::distinct(MARKERS, GT) %>%
            separate_gt(x = ., gt = "GT", exclude = "MARKERS", split.chunks = 1L) %>%
            dplyr::distinct(MARKERS, ALLELES) %>%
            dplyr::count(x = ., MARKERS)
        }

        if (rlang::has_name(data, "GT_VCF")) {
          data %<>%
            dplyr::select(MARKERS, GT_VCF) %>%
            dplyr::filter(MARKERS %in% sampled.markers) %>%
            dplyr::filter(GT_VCF != "./.") %>%
            dplyr::distinct(MARKERS, GT_VCF) %>%
            separate_gt(x = ., gt = "GT_VCF", exclude = "MARKERS", split.chunks = 1L) %>%
            dplyr::distinct(MARKERS, ALLELES) %>% # Here read alleles, not haplotypes
            dplyr::count(x = ., MARKERS)
        }

        if (rlang::has_name(data, "GT_VCF_NUC")) {
          data %<>%
            dplyr::select(MARKERS, GT_VCF_NUC) %>%
            dplyr::filter(GT_VCF_NUC != "./.") %>%
            dplyr::filter(MARKERS %in% sampled.markers) %>%
            dplyr::distinct(MARKERS, GT_VCF_NUC) %>%
            separate_gt(x = ., gt = "GT_VCF_NUC", exclude = "MARKERS", split.chunks = 1L) %>%
            dplyr::distinct(MARKERS, ALLELES) %>%
            dplyr::count(x = ., MARKERS)
        }

        # if (small.panel) {
        n.allele <- dplyr::filter(data, n > 2)
        if (nrow(n.allele) == n.markers) {
          data <- FALSE
          if (verbose) message("Data is multi-allelic")
        } else {
          if (verbose) message("Data is bi-allelic")
          if (max(data$n) > 2) {
            cli::cli_alert_info("Note: more than 2 types of alleles/nucleotides detected")
            cli::cli_alert_info("artifact/biological ? run radr::detect_biallelic_problem for more details")
          }
          data <- TRUE
        }
      }
    }
  }
  return(data)
} # End detect_biallelic_markers
